name: release

on:
  workflow_dispatch:
    inputs:
      publishPreRelease:
        description: 'Publish a pre-release ?'
        required: true
        type: choice
        options:
          - 'true'
          - 'false'
        default: 'false'
      publishToMarketPlace:
        description: 'Publish to VS Code Marketplace ?'
        required: true
        type: choice
        options:
          - 'true'
          - 'false'
        default: 'true'
      publishToOVSX:
        description: 'Publish to OpenVSX Registry ?'
        required: true
        type: choice
        options:
          - 'true'
          - 'false'
        default: 'true'

jobs:
  packaging-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout vscode-yaml
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          path: release
          node-version: 20
      - name: Install dependencies
        run: |
          npm install -g typescript "yarn" "@vscode/vsce" "ovsx"
          echo "EXT_VERSION=$(cat package.json | jq -r .version)" >> $GITHUB_ENV
      - name: Build vscode-yaml
        uses: coactions/setup-xvfb@b6b4fcfb9f5a895edadc3bc76318fae0ac17c8b3 #v1.0.1
        with:
          run: |
            yarn install
            yarn run build
            yarn run check-dependencies
      - name: Run Unit Tests
        uses: coactions/setup-xvfb@b6b4fcfb9f5a895edadc3bc76318fae0ac17c8b3 #v1.0.1
        with:
          run: yarn test --silent
      - name: Package
        run: |
          vsce package -o vscode-yaml-${{ env.EXT_VERSION }}-${GITHUB_RUN_NUMBER}.vsix
          sha256sum *.vsix > vscode-yaml-${{ env.EXT_VERSION }}-${GITHUB_RUN_NUMBER}.vsix.sha256
          ls -lash *.vsix *.sha256
      - name: Upload VSIX Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: vscode-yaml
          path: vscode-yaml-${{ env.EXT_VERSION }}-${{github.run_number}}*.vsix
          if-no-files-found: error
      - name: Publish to GH Release Tab
        if: ${{ inputs.publishToMarketPlace == 'true' && inputs.publishToOVSX == 'true' }}
        uses: "marvinpinto/action-automatic-releases@919008cf3f741b179569b7a6fb4d8860689ab7f0"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ env.EXT_VERSION }}"
          draft: true
          files: |
            vscode-yaml-${{ env.EXT_VERSION }}-${{github.run_number}}*.vsix
            vscode-yaml-${{ env.EXT_VERSION }}-${{github.run_number}}*.sha256

  release-job:
    if: ${{ inputs.publishToMarketPlace == 'true' || inputs.publishToOVSX == 'true' }}
    environment: ${{ (inputs.publishToMarketPlace == 'true' || inputs.publishToOVSX == 'true') && 'release' || 'pre-release' }}
    runs-on: ubuntu-latest
    needs: packaging-job
    steps:
    - name: Checkout vscode-yaml
      uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Install dependencies
      run: |
        npm install -g typescript "yarn" "@vscode/vsce" "ovsx"
        echo "EXT_VERSION=$(cat package.json | jq -r .version)" >> $GITHUB_ENV
    - name: Download VSIX Artifacts
      uses: actions/download-artifact@v4
    - name: Publish to VS Code Marketplace
      if: ${{ github.event_name == 'schedule' || inputs.publishToMarketPlace == 'true' || inputs.publishPreRelease == 'true' }}
      run: |
          vsce publish --packagePath vscode-yaml/vscode-yaml-${{ env.EXT_VERSION }}-${GITHUB_RUN_NUMBER}.vsix -p
    - name: Publish to OpenVSX Registry
      if: ${{ github.event_name == 'schedule' || inputs.publishToOVSX == 'true' || inputs.publishPreRelease == 'true' }}
      run: |
          ovsx publish --packagePath vscode-yaml/vscode-yaml-${{ env.EXT_VERSION }}-${GITHUB_RUN_NUMBER}.vsix -p
